name: Test Setup

on:
  push:
    branches: ["*"]
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:

   # Setup & Configuration
  SetupWin:
    name: "Windows test of  >> $env:GITHUB_OUTPUT"
    runs-on: windows-latest
    outputs:
      TestVariableWindows: ${{ steps.nkdagility.outputs.TestVariable }}      
    steps:
    - name: "Build NKDAgility Outputs"
      shell: pwsh
      id: nkdagility
      run: |
            echo "TestVariable=sucess" >> $env:GITHUB_OUTPUT

   # Setup & Configuration
  SetupUbntu:
    name: "Ubuntu test of  >> $env:GITHUB_OUTPUT"
    runs-on: ubuntu-latest
    outputs:
      TestVariableUbuntu: ${{ steps.nkdagility.outputs.TestVariable }}      
    steps:
    - name: "Build NKDAgility Outputs"
      shell: pwsh
      id: nkdagility
      run: |
            echo "TestVariable=sucess" >> $env:GITHUB_OUTPUT


  # Setup Validator
  SetupSummeryStage:
    name: "Output Data"
    runs-on: ubuntu-latest
    needs: [SetupWin, SetupUbntu]
    steps:
    - name: "Show Summery"
      if: always()
      shell: pwsh
      id: nkdagility-summery
      run: |
            $markdown = @"
                 - TestVariableWindows: ${{needs.SetupWin.outputs.TestVariableWin}}
                 - TestVariableUbuntu: ${{needs.SetupUbntu.outputs.TestVariableUn}}
            "@
            echo $markdown >> $Env:GITHUB_STEP_SUMMARY
